// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpE5U8kIoHxWWX7q_SsSTDrr0ywln98n4',
    appId: '1:543124166256:web:d6edaf47db66aba28bc6b5',
    messagingSenderId: '543124166256',
    projectId: 'pharmacy-182b8',
    authDomain: 'pharmacy-182b8.firebaseapp.com',
    storageBucket: 'pharmacy-182b8.appspot.com',
    measurementId: 'G-0CJHM34SBY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsuW50x-WJ9f0Nxtl_E5FNTYf_jV5AVqA',
    appId: '1:543124166256:android:c7420e381d2ee0758bc6b5',
    messagingSenderId: '543124166256',
    projectId: 'pharmacy-182b8',
    storageBucket: 'pharmacy-182b8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuQmPHmNGSTJC9R7DR7i1gDfSLb7JtSr0',
    appId: '1:543124166256:ios:f8be209d3a1974fb8bc6b5',
    messagingSenderId: '543124166256',
    projectId: 'pharmacy-182b8',
    storageBucket: 'pharmacy-182b8.appspot.com',
    iosBundleId: 'com.example.pharmacyManagementSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuQmPHmNGSTJC9R7DR7i1gDfSLb7JtSr0',
    appId: '1:543124166256:ios:f8be209d3a1974fb8bc6b5',
    messagingSenderId: '543124166256',
    projectId: 'pharmacy-182b8',
    storageBucket: 'pharmacy-182b8.appspot.com',
    iosBundleId: 'com.example.pharmacyManagementSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDpE5U8kIoHxWWX7q_SsSTDrr0ywln98n4',
    appId: '1:543124166256:web:9d437d4864e2c8188bc6b5',
    messagingSenderId: '543124166256',
    projectId: 'pharmacy-182b8',
    authDomain: 'pharmacy-182b8.firebaseapp.com',
    storageBucket: 'pharmacy-182b8.appspot.com',
    measurementId: 'G-ZJ7JL1L9MD',
  );
}
